//This file is automatically generated. DO NOT EDIT!
using System;
using RobotRaconteur;
using System.Collections.Generic;

namespace arduino2_interface
{
[RobotRaconteurServiceObjectInterface()]
public interface arduino2
{
    void setPotentiometer(int motor, int speed);
}

}
